version = 0.1

[default.global.parameters]
stack_name = "publish-data-receipt"
s3_bucket = "mytiki-core-ocean-cf-deploy"
s3_prefix = "publish/data/receipt"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_NAMED_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = []
