Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        Authorizers:
          CoreAwsAuthorizer:
            DisableFunctionDefaultPermissions: True
            FunctionArn: arn:aws:lambda:us-east-2:920781344533:function:core-aws-authorizer
            FunctionPayloadType: REQUEST
            Identity:
              Headers:
                - Authorization
      BinaryMediaTypes:
        - image/png
        - image/jpg
      Cors: "'*'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "TIKI Publish Receipt API"
          version: "1.0"
        paths:
          "/receipt/{receiptId}":
            post:
              parameters:
                - in: "path"
                  name: "receiptId"
                  required: true
                  type: "string"
              security:
                - CoreAwsAuthorizer: []
              x-amazon-apigateway-integration:
                type: aws
                credentials: "arn:aws:iam::920781344533:role/APIGatewayS3ProxyPolicy"
                uri: "arn:aws:apigateway:us-east-2:s3:path/com.mytiki.publish.data.images.test/{address}/{receiptId}/{requestId}"
                passthroughBehavior: "when_no_templates"
                httpMethod: "POST"
                requestParameters:
                  integration.request.path.receiptId: method.request.path.receiptId
                  integration.request.path.requestId: context.requestId
                  integration.request.path.address: context.authorizer.id
                responses:
                  - statusCode: "200"
                    responseTemplates:
                      application/json: ""
