AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Extract data from receipt images.

Resources:
  StateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: publish-data-receipt-textract
      Type: STANDARD
      DefinitionUri: ../../states/extract_receipt.json
      Tracing:
        Enabled: true
      Events:
        S3Event:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail:
                bucket:
                  name:
                    - com.mytiki.publish.data.images.test